name: prepare nim

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: nimlang/nim:latest
            options: --user 1001
        
        steps:
            - uses: actions/checkout@v4
            - name : Tests
              run: |
                nimble develop -y
                nim c -r flont/tester.nim